Layout: /_layout.cshtml
SiteTitle: Blazor University
EditRoot: https://github.com/TimeWarp-Enterprises/blazor-university/edit/main/input
# PostSources: "posts/**/*.{md,cshtml,html}" # This requires quotes becuase of the `{}` characters
# SourceFiles:
